### ISSUE TITLE
Wrong Katakana unicode script

### ISSUE THREAD

**Issue by rhalaly** [mrabarnett/mrab-regex#536] opened 2024-06-26 11:01 UTC
the regex `\p{Katakana}` should support the range `\u30A0-\u30FF` per regex documentation.

And while Regex101 can match this example:
![image](https://github.com/mrabarnett/mrab-regex/assets/8597700/6c83cacc-9f78-48d7-a951-3512cbdbf3ea)

The Python code isn't:

```python
print(regex.match(r'\p{Katakana}', "ー"))     # Output: None
```

This character Unicode is `\u30FC` which **should** be in range.

So, the expected output should be `[('ー', 0, 1)]`

**Comment by mrabarnett** [comment] 2024-06-26 15:31
The regex documentation states:

    """If the short form \p{value} is used, the properties are checked in the order: General_Category, Script, Block, binary property"""
  
"Katakana" isn't a value in the `General_Category` property, but it is a value in the `Script` property.

Therefore, `\p{Katakana}` is equivalent to `\p{Script:Katakana}`.

`'\u30FC'` doesn't match `\p{Script:Katakana}`, but it does match `\p{Block:Katakana}`.

The current version of Unicode is 15.1.0 and for the `Script` property there are these entries:

```
30A1..30FA    ; Katakana # Lo  [90] KATAKANA LETTER SMALL A..KATAKANA LETTER VO
30FD..30FE    ; Katakana # Lm   [2] KATAKANA ITERATION MARK..KATAKANA VOICED ITERATION MARK
```

Notice that `30FC` is not in those ranges.

Not a bug.

**Closed as completed by mrabarnett** 2024-06-26 15:31 UTC

**Comment by rhalaly** [comment] 2024-06-26 15:47
@mrabarnett thanks for the fast response. I wasn't aware that there is Katakana as Script with different ranges than the Block.

Can you please refer me to the Unicode document about the Katakana as Script that you quote from?

**Comment by mrabarnett** [comment] 2024-06-26 16:32
Here's a link to some text on the Unicode Consortium's site:

https://www.unicode.org/reports/tr24/#:~:text=However%2C%20blocks%20and%20scripts%20differ%20in%20the%20following,scripts%20may%20be%20encoded%20in%20the%20same%20block.

**Comment by facelessuser** [comment] 2024-06-26 16:32
It should be noted that there is a difference between script and script extensions as well. I think script extensions does include `\u30FC` while scripts does not. I believe some implementations now return script extensions as the default instead of scripts as the former is considered better. Should Regex consider this moving forward?

**Comment by facelessuser** [comment] 2024-06-26 16:52
Here is a reference where Perl notes they now return script extension when using the "single" form instead of script: https://perldoc.perl.org/perlunicode#Scripts.

**Comment by rhalaly** [comment] 2024-06-26 17:38
@mrabarnett thank you! 
@facelessuser Thanks, that is what I thought should happen here as well, as I see in some regex in other languages that they use `Katakana` script as `\u30A0-\u30FF`

**Comment by facelessuser** [comment] 2024-06-26 18:17
Yes, script extensions does use the range `\u30a0-\u30ff`.  `\u30FC` is specifically found in the following section and is shared between `hiragana` and `katakana`.

```
# Script_Extensions=Hira Kana

3031..3035    ; Hira Kana # Lm   [5] VERTICAL KANA REPEAT MARK..VERTICAL KANA REPEAT MARK LOWER HALF
3099..309A    ; Hira Kana # Mn   [2] COMBINING KATAKANA-HIRAGANA VOICED SOUND MARK..COMBINING KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK
309B..309C    ; Hira Kana # Sk   [2] KATAKANA-HIRAGANA VOICED SOUND MARK..KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK
30A0          ; Hira Kana # Pd       KATAKANA-HIRAGANA DOUBLE HYPHEN
30FC          ; Hira Kana # Lm       KATAKANA-HIRAGANA PROLONGED SOUND MARK
FF70          ; Hira Kana # Lm       HALFWIDTH KATAKANA-HIRAGANA PROLONGED SOUND MARK
FF9E..FF9F    ; Hira Kana # Lm   [2] HALFWIDTH KATAKANA VOICED SOUND MARK..HALFWIDTH KATAKANA SEMI-VOICED SOUND MARK
```
Reference: https://www.unicode.org/Public/15.1.0/ucd/ScriptExtensions.txt
